const datosEstudiantes = [
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Contaduría Pública", "Estudiantes": 39},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Gerencia Financiera Y Contable", "Estudiantes": 4},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Gerencia Para La Transformación Digital", "Estudiantes": 51},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Ingeniería De Sistemas Y Computación", "Estudiantes": 670},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Contaduría Pública", "Estudiantes": 670},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Ingeniería De Sistemas Y Computación", "Estudiantes": 608},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Ingeniería Agronómica", "Estudiantes": 318},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Psicología", "Estudiantes": 368},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Ingeniería de Software", "Estudiantes": 375},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Especialización En Gerencia Para El Desarrollo Organizacional", "Estudiantes": 14},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Educación Ambiental Y Desarrollo De La Comunidad", "Estudiantes": 8},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Licenciatura En Educación Física, Recreación Y Deportes ", "Estudiantes": 134},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Ingeniería Industrial", "Estudiantes": 218},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Administración De Empresas", "Estudiantes": 634},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Ingeniería Electrónica", "Estudiantes": 334},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Ingeniería Industrial", "Estudiantes": 480},
  {"MUNICIPIO_PROGRAMA": "Zipaquirá", "Programa": "Música", "Estudiantes": 214},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Ingeniería De Sistemas Y Computación", "Estudiantes": 677},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Ingeniería Mecatrónica", "Estudiantes": 180},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Administración De Empresas", "Estudiantes": 633},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Contaduría Pública", "Estudiantes": 561},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Doctorado En Ciencias De La Educación", "Estudiantes": 18},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Maestría En Ciencias Ambientales", "Estudiantes": 4},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Maestría En Educación", "Estudiantes": 5},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Ingeniería De Sistemas", "Estudiantes": 68},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Ingeniería De Sistemas", "Estudiantes": 8},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Ingeniería De Sistemas", "Estudiantes": 57},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Zootecnia", "Estudiantes": 324},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Profesional En Ciencias Del Deporte", "Estudiantes": 631},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Ingeniería De Sistemas Y Computación", "Estudiantes": 287},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Ingeniería Agronómica", "Estudiantes": 289},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Licenciatura En Ciencias Sociales", "Estudiantes": 171},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Administración De Empresas", "Estudiantes": 532},
  {"MUNICIPIO_PROGRAMA": "Chía", "Programa": "Contaduría Pública", "Estudiantes": 321},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Administración De Empresas", "Estudiantes": 137},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Contaduría Pública", "Estudiantes": 386},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Tecnología En Desarrollo De Software", "Estudiantes": 42},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Gestión Pública", "Estudiantes": 45},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Infraestructura Y Seguridad De Redes", "Estudiantes": 10},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Marketing Digital", "Estudiantes": 22},
  {"MUNICIPIO_PROGRAMA": "Soacha", "Programa": "Ingeniería Topográfica Y Geomática ", "Estudiantes": 22},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Licenciatura En Educación Básica Con Énfasis En Ciencias Sociales", "Estudiantes": 2},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Metodologías De Calidad Para El Desarrollo Del Software", "Estudiantes": 24},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Agroecología Y Desarrollo Agro ecoturístico", "Estudiantes": 10},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Agronegocios Sostenibles", "Estudiantes": 10},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Analítica Aplicada A Negocios", "Estudiantes": 32},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Especialización En Analítica Y Ciencia De Datos", "Estudiantes": 22},
  {"MUNICIPIO_PROGRAMA": "Fusagasuga", "Programa": "Tecnología En Cartografía", "Estudiantes": 2},
  {"MUNICIPIO_PROGRAMA": "Girardot", "Programa": "Administración De Empresas", "Estudiantes": 457},
  {"MUNICIPIO_PROGRAMA": "Girardot", "Programa": "Ingeniería De Software", "Estudiantes": 256},
  {"MUNICIPIO_PROGRAMA": "Girardot", "Programa": "Ingeniería Ambiental", "Estudiantes": 253},
  {"MUNICIPIO_PROGRAMA": "Girardot", "Programa": "Enfermería", "Estudiantes": 390},
  {"MUNICIPIO_PROGRAMA": "Facatativá", "Programa": "Ingeniería Ambiental", "Estudiantes": 322},
  {"MUNICIPIO_PROGRAMA": "Girardot", "Programa": "Tecnología En Gestión Turística Y Hotelera", "Estudiantes": 3},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Administración De Empresas", "Estudiantes": 281},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Medicina Veterinaria Y Zootecnia ", "Estudiantes": 41},
  {"MUNICIPIO_PROGRAMA": "Ubaté", "Programa": "Zootecnia", "Estudiantes": 275}
];

