// datos-tableros.js
// Base de datos de tableros institucionales

const tableros = [
  // ==============================================================================
  // MACROPROCESO: ESTRATÉGICO
  // ==============================================================================
  {
    "id": 9,
    "titulo": "Convenios",
    "area": "Proyectos Especiales y Relaciones Interinstitucionales",
    "macroproceso": "Estratégico",
    "subproceso": "Proyectos Especiales y Relaciones Interinstitucionales",
    "rol": "Administrativo",
    "url": "Sí",
    "fechaActualizacion": "Reporte Convenios",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Proyectos Especiales y Relaciones Interinstitucionales",
    "descripcion": "Dashboard institucional de Convenios con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Convenios",
    "resumenDataset": "Datos relacionados con Convenios para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 10,
    "titulo": "Eventos UCundinamarca - Interacción Redes Sociales",
    "area": "Comunicaciones",
    "macroproceso": "Estratégico",
    "subproceso": "Comunicaciones",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYTZkZDlmZTYtZDRiNi00ODMxLWFmYTMtOTlkMzU0MjdlYzA0IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2021",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Eventos UCundinamarca - Interacción Redes Sociales con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Eventos_UCundinamarca_Interacci_n_Redes_Sociales",
    "resumenDataset": "Datos relacionados con Eventos UCundinamarca - Interacción Redes Sociales para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 22,
    "titulo": "Sistema de Gestión de Seguridad de la Información - SGSI",
    "area": "Sistemas Integrados",
    "macroproceso": "Estratégico",
    "subproceso": "Sistemas Integrados",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYzAyMTE5MzktZWNhNS00ZmQ0LWFjNmMtYjNmNmE4ODViYTQ5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2023",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Sistema de Gestión de Seguridad de la Información - SGSI con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Sistema_de_Gesti_n_de_Seguridad_de_la_Informaci_n_SGSI",
    "resumenDataset": "Datos relacionados con Sistema de Gestión de Seguridad de la Información - SGSI para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 27,
    "titulo": "Fanpage Facultades UCundinamarca",
    "area": "Comunicaciones",
    "macroproceso": "Estratégico",
    "subproceso": "Comunicaciones",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNzBhYmE1ZGItZTM4YS00MzdiLWExNmUtOWVkMTI3NmRmODUxIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "29/09/2023 6:09:07",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Fanpage Facultades UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Fanpage_Facultades_UCundinamarca",
    "resumenDataset": "Datos relacionados con Fanpage Facultades UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 46,
    "titulo": "Sistema de Gestión Ambiental Indicadores",
    "area": "Sistemas Integrados",
    "macroproceso": "Estratégico",
    "subproceso": "Sistemas Integrados",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMDE0YTAyN2ItZWVjZi00MGMyLTkwZWYtOTdlYmNlZTU2MDVmIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "No especificada",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Sistema de Gestión Ambiental Indicadores con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Sistema_de_Gesti_n_Ambiental_Indicadores",
    "resumenDataset": "Datos relacionados con Sistema de Gestión Ambiental Indicadores para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 47,
    "titulo": "Plan Integral de Gestión Ambiental -PIGA-",
    "area": "Sistemas Integrados",
    "macroproceso": "Estratégico",
    "subproceso": "Sistemas Integrados",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNzBiM2U2MDgtNTRlNy00ZmIxLTliZGEtZWYwYzZhNjY5NjFkIiwidCI6IjE5YzMxMzBjLTZjNTgtNGRiZi1iOWEyLTY3OWQzZDBlN2YwMCIsImMiOjR9",
    "fechaActualizacion": "2022-2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas Integrados",
    "descripcion": "Dashboard institucional de Plan Integral de Gestión Ambiental -PIGA- con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Plan_Integral_de_Gesti_n_Ambiental_PIGA_",
    "resumenDataset": "Datos relacionados con Plan Integral de Gestión Ambiental -PIGA- para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 58,
    "titulo": "Dirección de Planeación Institucional - Boletín Estadístico XV",
    "area": "Planeación Institucional",
    "macroproceso": "Estratégico",
    "subproceso": "Planeación Institucional",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZTYyOWU0ZGQtNzUxNS00MTdjLTgxMTMtODRjNzc4NThkMTYxIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Planeación Institucional",
    "descripcion": "Dashboard institucional de Dirección de Planeación Institucional - Boletín Estadístico XV con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Direcci_n_de_Planeaci_n_Institucional_Bolet_n_Estad_stico_XV",
    "resumenDataset": "Datos relacionados con Dirección de Planeación Institucional - Boletín Estadístico XV para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 59,
    "titulo": "Indicadores Deserción y Permanencia",
    "area": "Planeación Institucional",
    "macroproceso": "Estratégico",
    "subproceso": "Planeación Institucional",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYTY0MDk3MDAtZDIzMy00MTk3LThlZmItYzgyNzk3YWU3YjNhIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Planeación Institucional",
    "descripcion": "Dashboard institucional de Indicadores Deserción y Permanencia con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Indicadores_Deserci_n_y_Permanencia",
    "resumenDataset": "Datos relacionados con Indicadores Deserción y Permanencia para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 60,
    "titulo": "UCundinamarca - Calendario Institucional 2025",
    "area": "Planeación Institucional",
    "macroproceso": "Estratégico",
    "subproceso": "Planeación Institucional",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiOTQzMDgxODgtMTFkYS00YWU2LWE2NTAtMjI0OTFiMTBmNWY5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Planeación Institucional",
    "descripcion": "Dashboard institucional de UCundinamarca - Calendario Institucional 2025 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "UCundinamarca_Calendario_Institucional_2025",
    "resumenDataset": "Datos relacionados con UCundinamarca - Calendario Institucional 2025 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 61,
    "titulo": "Campo de Aprendizaje Institucional - Encuentros Dialógicos y Formativos",
    "area": "Planeación Institucional",
    "macroproceso": "Estratégico",
    "subproceso": "Planeación Institucional",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMjFlYmIzOTUtMDcyMy00MGNiLTllZjktNTY2ZjM2ZjgxMmVlIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "No especificada (Uso para consulta)",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Planeación Institucional",
    "descripcion": "Dashboard institucional de Campo de Aprendizaje Institucional - Encuentros Dialógicos y Formativos con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Campo_de_Aprendizaje_Institucional_Encuentros_Dial_gicos_y_Formativos",
    "resumenDataset": "Datos relacionados con Campo de Aprendizaje Institucional - Encuentros Dialógicos y Formativos para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  // ==============================================================================
  // MACROPROCESO: MISIONAL
  // ==============================================================================
  {
    "id": 1,
    "titulo": "Experiencia de Aprendizaje Online con Efectividad",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMWZiOWUyMjktODBiNi00ODRjLWJlNTUtOGE2ODA4NTM0NjljIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "5/12/2025 8:05",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Experiencia de Aprendizaje Online con Efectividad con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Experiencia_de_Aprendizaje_Online_con_Efectividad",
    "resumenDataset": "Datos relacionados con Experiencia de Aprendizaje Online con Efectividad para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 3,
    "titulo": "Monitorías",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Estudiante",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYTk4ZWExYjMtYTNkYS00YmQzLTg4MWItZjA0N2VhNDRkMjQzIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "IPA 2023",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Monitorias con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Monitorias",
    "resumenDataset": "Datos relacionados con Monitorias para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 4,
    "titulo": "Inscripciones UCundinamarca",
    "area": "Admisiones y Registro",
    "macroproceso": "Misional",
    "subproceso": "Admisiones y Registro",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMmFmNWViOWMtMjIzMy00NTQ1LTgxYmEtZDVmZDFhOTkwYzdiIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2022-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Inscripciones UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Inscripciones_UCundinamarca",
    "resumenDataset": "Datos relacionados con Inscripciones UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 5,
    "titulo": "Horas de Interacción Social",
    "area": "Interacción Social Universitaria",
    "macroproceso": "Misional",
    "subproceso": "Interacción Social Universitaria",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMGE3NGVjMWEtYzk1Yy00YTQ2LWJmNDYtYjc2OTZkYTc0NjllIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "12/01/2024 8:05:52",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Horas de Interacción Social con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Horas_de_Interacci_n_Social",
    "resumenDataset": "Datos relacionados con Horas de Interacción Social para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 7,
    "titulo": "Grupos Académicos",
    "area": "Ciencia, Tecnología e Innovación",
    "macroproceso": "Misional",
    "subproceso": "Ciencia, Tecnología e Innovación",
    "rol": "Estudiante",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZmI5MTZiZGEtMzE0Ny00NGZjLTg1NDctNzBlN2E5M2FiOTUzIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 6:04",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Grupos Académicos con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Grupos_Acad_micos",
    "resumenDataset": "Datos relacionados con Grupos Académicos para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 11,
    "titulo": "Tasa de Graduación",
    "area": "Graduados",
    "macroproceso": "Misional",
    "subproceso": "Graduados",
    "rol": "Estudiante",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiODNiNmI2MjUtY2Y1OC00M2QzLWI4YzItYmFlZTliODRhYjI5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection5303c09078171b834cd7",
    "fechaActualizacion": "2023",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Tasa de Graduación con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Tasa_de_Graduaci_n",
    "resumenDataset": "Datos relacionados con Tasa de Graduación para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 12,
    "titulo": "Desarrollo de la Lengua Extranjera Inglés de la UCundinamarca",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNDliNzdjMzAtMTg1MC00NDY2LTkxZjItYTA0YzQ2MmUyOWVlIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "No especificada",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Desarrollo de la Lengua Extranjera Inglés de la UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Desarrollo_de_la_Lengua_Extranjera_Ingl_s_de_la_UCundinamarca",
    "resumenDataset": "Datos relacionados con Desarrollo de la Lengua Extranjera Inglés de la UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 13,
    "titulo": "Plan de Aprendizaje Digital",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZGE3MWY4OGYtYTFmMi00NTYwLThhZjYtOGFmNTE5OWFhYWFiIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "04/12/2025 11:03:44",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Plan de Aprendizaje Digital con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Plan_de_Aprendizaje_Digital",
    "resumenDataset": "Datos relacionados con Plan de Aprendizaje Digital para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 14,
    "titulo": "Seguimiento CADI 2020-2",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMzU4OWQ2ODAtOGNiZS00MTE0LWE2ZWQtN2E3MDcwMzA0OWM4IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2020-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Seguimiento CADI 2020-2 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Seguimiento_CADI_2020_2",
    "resumenDataset": "Datos relacionados con Seguimiento CADI 2020-2 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 15,
    "titulo": "Ejecución CADI 2021-1",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMGY4MTYxODUtOTQ2ZC00NGU4LWEzMzUtMWJiNzZmZGE0MWY5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2021-1",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Ejecución CADI 2021-1 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Ejecuci_n_CADI_2021_1",
    "resumenDataset": "Datos relacionados con Ejecución CADI 2021-1 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 16,
    "titulo": "Analítica Resultados Saber PRO - Saber TyT 2018-2019-2020-2021",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNWQ4MmQ3NzAtNDQwYS00YmEyLThhODYtNmViMzkzYjdkMGM1IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSectionbb5377277b1ac3a3c699",
    "fechaActualizacion": "2021",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Analítica Resultados Saber PRO - Saber TyT 2018-2019-2020-2021 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Anal_tica_Resultados_Saber_PRO_Saber_TyT_2018_2019_2020_2021",
    "resumenDataset": "Datos relacionados con Analítica Resultados Saber PRO - Saber TyT 2018-2019-2020-2021 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 17,
    "titulo": "Resultados del Análisis y Sistematización de los Aportes al Reglamento Estudiantil V3",
    "area": "Bienestar Universitario",
    "macroproceso": "Misional",
    "subproceso": "Bienestar Universitario",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNzNhZjE4NTgtZDlhZi00ZTMxLWEzZGEtZTVkOGQyMTg4MTFjIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2021-2",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Resultados del Análisis y Sistematización de los Aportes al Reglamento Estudiantil V3 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Resultados_del_An_lisis_y_Sistematizaci_n_de_los_Aportes_al_Reglamento_Estudiantil_V3",
    "resumenDataset": "Datos relacionados con Resultados del Análisis y Sistematización de los Aportes al Reglamento Estudiantil V3 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 20,
    "titulo": "ICFES Saber PRO y TyT UCundinamarca",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNzk2YTg3MTctOTk3My00ZDliLWI0MDEtZGM4MWFkMjE2ZWZiIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2022",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de ICFES Saber PRO y TyT UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "ICFES_Saber_PRO_y_TyT_UCundinamarca",
    "resumenDataset": "Datos relacionados con ICFES Saber PRO y TyT UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 21,
    "titulo": "Bienestar Universitario Digital",
    "area": "Bienestar Universitario",
    "macroproceso": "Misional",
    "subproceso": "Bienestar Universitario",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMWE4YzYzOWUtZThhNy00MGJmLWIxODctYTNiYWE3NDJmZDlkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "4/12/2025 6:43",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Bienestar Universitario Digital con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Bienestar_Universitario_Digital",
    "resumenDataset": "Datos relacionados con Bienestar Universitario Digital para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 23,
    "titulo": "Inteligencia Emocional UCundinamarca Seccional Girardot",
    "area": "Bienestar Universitario",
    "macroproceso": "Misional",
    "subproceso": "Bienestar Universitario",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiOTk3ODg3ODctYmU1Yy00Y2QyLThkNTItMzkxMWE5NTMzNDlkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2022-1",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Inteligencia Emocional UCundinamarca Seccional Girardot con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Inteligencia_Emocional_UCundinamarca_Seccional_Girardot",
    "resumenDataset": "Datos relacionados con Inteligencia Emocional UCundinamarca Seccional Girardot para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 24,
    "titulo": "Proceso de Digitalización CADIs",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYTVjYzY5YjMtNDg1My00NWQzLTk3OTYtMDY5OGY4MzE4N2U1IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2022-1",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Proceso de Digitalización CADIs con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Proceso_de_Digitalizaci_n_CADIs",
    "resumenDataset": "Datos relacionados con Proceso de Digitalización CADIs para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 28,
    "titulo": "Matriculados Totales",
    "area": "Admisiones y Registro",
    "macroproceso": "Misional",
    "subproceso": "Admisiones y Registro",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMjdlZWI3Y2EtNjIwOS00Y2Y5LTgwOGEtMWE2NDA3OWYwOGM5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "1992-2022",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Matriculados Totales con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Matriculados_Totales",
    "resumenDataset": "Datos relacionados con Matriculados Totales para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 29,
    "titulo": "Asesor Disciplinar",
    "area": "Formación y Aprendizaje",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMzM4YTllZGUtOGQ1Yy00MWQ5LWFkN2UtNWFhMmViY2MxZTVkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 4:08",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Formación y Aprendizaje",
    "descripcion": "Dashboard institucional de Asesor Disciplinar con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Asesor_Disciplinar",
    "resumenDataset": "Datos relacionados con Asesor Disciplinar para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 30,
    "titulo": "CAI Cátedra Generación Siglo XXI",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMWFkODZhODgtOTVmZi00ZTFhLTlmZjgtMDlhZjlhNjA0N2YwIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 9:06",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de CAI Cátedra Generación Siglo XXI con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "CAI_C_tedra_Generaci_n_Siglo_XXI",
    "resumenDataset": "Datos relacionados con CAI Cátedra Generación Siglo XXI para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 31,
    "titulo": "CAI Viviendo el MEDIT",
    "area": "Oficina de Desarrollo Académico",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZjdhZmFjYjEtZTUyMi00NzUwLTg0YzItMjEyYjgyNWZjYTBkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "16/12/2024",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Desarrollo Académico",
    "descripcion": "Dashboard institucional de CAI Viviendo el MEDIT con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "CAI_Viviendo_el_MEDIT",
    "resumenDataset": "Datos relacionados con CAI Viviendo el MEDIT para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 32,
    "titulo": "Campo Multidimensional de Aprendizaje CMA - Pregrado",
    "area": "Oficina de Desarrollo Académico",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMzdlYjNhNDAtYzQzOC00ZmRhLTk5NTktNWQ2YzA4NGI5YTc0IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "26/11/2025 8:10:31",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Desarrollo Académico",
    "descripcion": "Dashboard institucional de Campo Multidimensional de Aprendizaje CMA - Pregrado con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Campo_Multidimensional_de_Aprendizaje_CMA_Pregrado",
    "resumenDataset": "Datos relacionados con Campo Multidimensional de Aprendizaje CMA - Pregrado para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 33,
    "titulo": "Diagnósticos y Nivelatorios",
    "area": "Oficina de Desarrollo Académico",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZWQwOTI0ZDYtZTYxNC00MGFmLWE1OTUtNTM4MzViZDcwNDNkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "27/06/2025 9:12:57",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Desarrollo Académico",
    "descripcion": "Dashboard institucional de Diagnósticos y Nivelatorios con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Diagn_sticos_y_Nivelatorios",
    "resumenDataset": "Datos relacionados con Diagnósticos y Nivelatorios para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 34,
    "titulo": "Ingresos al Campo Multidimensional de Aprendizaje",
    "area": "Oficina de Desarrollo Académico",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMDNjYzVmNjYtYzI4OS00NGEwLWJlNDgtODMzY2M2ZDMzY2Q2IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "17/06/2025 9:11:16",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Desarrollo Académico",
    "descripcion": "Dashboard institucional de Ingresos al Campo Multidimensional de Aprendizaje con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Ingresos_al_Campo_Multidimensional_de_Aprendizaje",
    "resumenDataset": "Datos relacionados con Ingresos al Campo Multidimensional de Aprendizaje para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 35,
    "titulo": "Monitorías (OEVD)",
    "area": "Oficina de Desarrollo Académico",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMjdlNTVkNmItMDMwZi00ZjlkLWJhNzktNWYwMWQyYWY4MGFjIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 10:05",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Desarrollo Académico",
    "descripcion": "Dashboard institucional de Monitorías (OEVD) con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Monitorias_OEVD_",
    "resumenDataset": "Datos relacionados con Monitorías (OEVD) para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 36,
    "titulo": "Tránsito de la Educación Media a la Educación Superior",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiN2IwOWQ0MTAtZjY1Mi00YmRjLTg2MmItYTJlYmZjZDk1YjY1IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "28/07/2024 9:03",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Tránsito de la Educación Media a la Educación Superior con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Tr_nsito_de_la_Educaci_n_Media_a_la_Educaci_n_Superior",
    "resumenDataset": "Datos relacionados con Tránsito de la Educación Media a la Educación Superior para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 37,
    "titulo": "Asesor Disciplinar (Detalle)",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiOTE5MTcyZjAtYjNkNy00ZTE0LTgyMDItNGQ0MGE4OTZlMDk0IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 8:09",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Asesor Disciplinar (Detalle) con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Asesor_Disciplinar_Detalle_",
    "resumenDataset": "Datos relacionados con Asesor Disciplinar (Detalle) para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 38,
    "titulo": "CAI Cátedra Generación Siglo 21 - Estrategia Institucional Saber PRO",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiNjQ3ODYwNzItZDRlMi00ZDljLTk1ODQtNjJlMGY1YTI2NTJjIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de CAI Cátedra Generación Siglo 21 - Estrategia Institucional Saber PRO con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "CAI_C_tedra_Generaci_n_Siglo_21_Estrategia_Institucional_Saber_PRO",
    "resumenDataset": "Datos relacionados con CAI Cátedra Generación Siglo 21 - Estrategia Institucional Saber PRO para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 39,
    "titulo": "Campo Multidimensional de Aprendizaje CMA - Posgrados",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiY2RiZTJjMzktNGVhOC00YmZhLWFkNzItNTUzOTlhZTYyNTc4IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "19/11/2025 12:32:41",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Campo Multidimensional de Aprendizaje CMA - Posgrados con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Campo_Multidimensional_de_Aprendizaje_CMA_Posgrados",
    "resumenDataset": "Datos relacionados con Campo Multidimensional de Aprendizaje CMA - Posgrados para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 40,
    "titulo": "Cursos Autogestionados",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiOTBhNThkMTktNmU0OC00YmM5LTkyNDktNGFjMTA5NGFmNTdmIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "26/08/2024 09:34:17",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Cursos Autogestionados con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Cursos_Autogestionados",
    "resumenDataset": "Datos relacionados con Cursos Autogestionados para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 41,
    "titulo": "Graduados UCundinamarca",
    "area": "Oficina de Graduados",
    "macroproceso": "Misional",
    "subproceso": "Graduados",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZjZkZmQ1MzUtMjA4Yy00OTIzLWE5N2QtMmU4NTE1Y2UwMWY5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 7:06",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Graduados",
    "descripcion": "Dashboard institucional de Graduados UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Graduados_UCundinamarca",
    "resumenDataset": "Datos relacionados con Graduados UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 42,
    "titulo": "Informe Final",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYzdiN2I2ZWQtOWY4ZS00MWJiLWIyODUtZTViY2Q0ZTc3NDc2IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "16/06/2025 5:37",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Informe Final con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Informe_Final",
    "resumenDataset": "Datos relacionados con Informe Final para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 43,
    "titulo": "Insignias Digitales",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYWQ1MmJiNzQtNzJkZS00MzYzLTg4YWEtMjFjOTAxNDMzYWJjIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "28/10/2025 7:07",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Insignias Digitales con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Insignias_Digitales",
    "resumenDataset": "Datos relacionados con Insignias Digitales para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 44,
    "titulo": "Inventario Recursos Educativos Digitales",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiN2JlODU1MGQtM2FiNi00NWU4LWI1YjItNWVmMGZlMmNlM2I5IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "No especificada",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Inventario Recursos Educativos Digitales con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Inventario_Recursos_Educativos_Digitales",
    "resumenDataset": "Datos relacionados con Inventario Recursos Educativos Digitales para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 45,
    "titulo": "Posgrados",
    "area": "Oficina de Educación Virtual y a Distancia",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMjFiNDQ4ODQtMWE4Mi00YjFmLWJiOTYtYWU1MGViNjQzOWI1IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "11/09/2024 4:53",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Oficina de Educación Virtual y a Distancia",
    "descripcion": "Dashboard institucional de Posgrados con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Posgrados",
    "resumenDataset": "Datos relacionados con Posgrados para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 55,
    "titulo": "Perfil Sociodemográfico de Estudiantes Actuales",
    "area": "Instituto de Posgrados",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMGE4MjRlOWUtMDM5MC00YmFlLWJlYTEtZTgxNGUzOGVmYTIwIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "Octubre 2023",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Instituto de Posgrados",
    "descripcion": "Dashboard institucional de Perfil Sociodemográfico de Estudiantes Actuales con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Perfil_Sociodemogr_fico_de_Estudiantes_Actuales",
    "resumenDataset": "Datos relacionados con Perfil Sociodemográfico de Estudiantes Actuales para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 56,
    "titulo": "Encuesta Satisfacción Programas",
    "area": "Instituto de Posgrados",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYjEyOTYyN2MtNmZhYy00YjAzLThjNDgtMmU3Yjg1OWM1ZTQwIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "11/12/2024",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Instituto de Posgrados",
    "descripcion": "Dashboard institucional de Encuesta Satisfacción Programas con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Encuesta_Satisfacci_n_Programas",
    "resumenDataset": "Datos relacionados con Encuesta Satisfacción Programas para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 57,
    "titulo": "Reporte de Opciones de Grado",
    "area": "Instituto de Posgrados",
    "macroproceso": "Misional",
    "subproceso": "Formación y Aprendizaje",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiODJlMjM2MTctOWI4NS00NzBjLWE4NTYtNDQxNzdkNzRhMWVmIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2024",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Instituto de Posgrados",
    "descripcion": "Dashboard institucional de Reporte de Opciones de Grado con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Reporte_de_Opciones_de_Grado",
    "resumenDataset": "Datos relacionados con Reporte de Opciones de Grado para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  // ==============================================================================
  // MACROPROCESO: APOYO
  // ==============================================================================
  {
    "id": 2,
    "titulo": "Horas Sustantivas de Docentes",
    "area": "Talento Humano",
    "macroproceso": "Apoyo",
    "subproceso": "Talento Humano",
    "rol": "Gestor",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZGYyZjdmZGUtMzZhZi00Zjk4LTkwOTQtOWVjNjVkOGUzMzNjIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "IPA 2023",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Horas Sustantivas de Docentes con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Horas_Sustantivas_de_Docentes",
    "resumenDataset": "Datos relacionados con Horas Sustantivas de Docentes para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 6,
    "titulo": "Matrícula Financiera UCundinamarca",
    "area": "Financiera",
    "macroproceso": "Apoyo",
    "subproceso": "Financiera",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYzgyNDZlYTItODk4NC00MzczLWE1ODctMTJhODcxYTRlZGVmIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "04/12/2025 10:01:57",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Matrícula Financiera UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Matr_cula_Financiera_UCundinamarca",
    "resumenDataset": "Datos relacionados con Matrícula Financiera UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 18,
    "titulo": "Sesiones Virtuales de la Dirección de Sistemas y Tecnología",
    "area": "Sistemas y Tecnología",
    "macroproceso": "Apoyo",
    "subproceso": "Sistemas y Tecnología",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYzU1YTY1ZTUtMDcxZC00N2M3LWI3ODItNmQwYTQ0MDQ3NWM3IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "04/12/2025 10:32:39",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Sesiones Virtuales de la Dirección de Sistemas y Tecnología con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Sesiones_Virtuales_de_la_Direcci_n_de_Sistemas_y_Tecnolog_a",
    "resumenDataset": "Datos relacionados con Sesiones Virtuales de la Dirección de Sistemas y Tecnología para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 19,
    "titulo": "Microsoft Teams UCundinamarca",
    "area": "Sistemas y Tecnología",
    "macroproceso": "Apoyo",
    "subproceso": "Sistemas y Tecnología",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiOTU2YWQwNDctYTRhZS00ZGZjLWFjMDAtMmNiNWZlMzM3ZDYzIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2023-2 (20/09/2023)",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Microsoft Teams UCundinamarca con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Microsoft_Teams_UCundinamarca",
    "resumenDataset": "Datos relacionados con Microsoft Teams UCundinamarca para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 25,
    "titulo": "Implementación Cursos Talento Humano",
    "area": "Talento Humano",
    "macroproceso": "Apoyo",
    "subproceso": "Talento Humano",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiM2FkODU4MDktNjVlOC00MGQ5LTk5MWEtMjBmZGViYjI2NDQ0IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "5/12/2025 5:37",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Implementación Cursos Talento Humano con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Implementaci_n_Cursos_Talento_Humano",
    "resumenDataset": "Datos relacionados con Implementación Cursos Talento Humano para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 26,
    "titulo": "Dirección de Bienes y Servicios",
    "area": "Bienes y Servicios",
    "macroproceso": "Apoyo",
    "subproceso": "Bienes y Servicios",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYjhiMzZlMWUtNWI3Zi00MGFmLTgzZjgtM2EyNDczNTg4MjZkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "12/11/2023 9:37:39",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Dirección de Bienes y Servicios con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Direcci_n_de_Bienes_y_Servicios",
    "resumenDataset": "Datos relacionados con Dirección de Bienes y Servicios para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 48,
    "titulo": "Seguimiento ABS",
    "area": "Bienes y Servicios",
    "macroproceso": "Apoyo",
    "subproceso": "Bienes y Servicios",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZTJkYjJlNmYtZjY3MC00Y2YxLWI2YzctNzNmMTUyYTlkNGU3IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Bienes y Servicios",
    "descripcion": "Dashboard institucional de Seguimiento ABS con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Seguimiento_ABS",
    "resumenDataset": "Datos relacionados con Seguimiento ABS para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 50,
    "titulo": "Ejecución Activa",
    "area": "Financiera",
    "macroproceso": "Apoyo",
    "subproceso": "Financiera",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiM2UzMWM0ODEtYmMwNC00NzUzLWEyM2YtOThiMzAwZjZmMzRlIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Financiera",
    "descripcion": "Dashboard institucional de Ejecución Activa con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Ejecuci_n_Activa",
    "resumenDataset": "Datos relacionados con Ejecución Activa para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 51,
    "titulo": "Ejecución Pasiva",
    "area": "Financiera",
    "macroproceso": "Apoyo",
    "subproceso": "Financiera",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMWE4NGI1N2EtNGY2OC00MmMyLTkzMjMtYWUxZjA5OTk2ZGVhIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "30/11/2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Financiera",
    "descripcion": "Dashboard institucional de Ejecución Pasiva con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Ejecuci_n_Pasiva",
    "resumenDataset": "Datos relacionados con Ejecución Pasiva para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 53,
    "titulo": "Plan Contratación Mensual 2025",
    "area": "Financiera",
    "macroproceso": "Apoyo",
    "subproceso": "Financiera",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiZmNkOWQ1MTItOTM0Yy00YjgyLWFkNGYtNzEwNjBmNzM3YWM2IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Financiera",
    "descripcion": "Dashboard institucional de Plan Contratación Mensual 2025 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Plan_Contrataci_n_Mensual_2025",
    "resumenDataset": "Datos relacionados con Plan Contratación Mensual 2025 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 62,
    "titulo": "Información para gestores del conocimiento UCundinamarca 2025-1",
    "area": "Talento Humano",
    "macroproceso": "Apoyo",
    "subproceso": "Talento Humano",
    "rol": "Gestor",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMThlNDcyY2EtNDNlMC00MTUyLWI0ODMtMjNkYTllMTFjODljIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "No especificada",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Información para gestores del conocimiento UCundinamarca 2025-1 con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Informaci_n_para_gestores_del_conocimiento_UCundinamarca_2025_1",
    "resumenDataset": "Datos relacionados con Información para gestores del conocimiento UCundinamarca 2025-1 para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  // ==============================================================================
  // MACROPROCESO: SEGUIMIENTO
  // ==============================================================================
  {
    "id": 8,
    "titulo": "Atención al Ciudadano (PQRSFyD)",
    "area": "Servicio de Atención al Ciudadano",
    "macroproceso": "Seguimiento",
    "subproceso": "Servicio de Atención al Ciudadano",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiMGM0MTY1OGQtZjkyYy00ZDIyLThmMzctZWYwMjdkYjA3NmU4IiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9&pageName=ReportSection",
    "fechaActualizacion": "2022",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Sistemas y Tecnología",
    "descripcion": "Dashboard institucional de Atención al Ciudadano (PQRSFyD) con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Atenci_n_al_Ciudadano_PQRSFyD_",
    "resumenDataset": "Datos relacionados con Atención al Ciudadano (PQRSFyD) para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 49,
    "titulo": "Matriz Estado de Avance Planes de Mejoramiento",
    "area": "Control Interno",
    "macroproceso": "Seguimiento",
    "subproceso": "Control Interno",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYzBmNDk1MGYtZjJiYi00OTBlLWI4ZDMtMWVhZDFjMDc0ZGUxIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "No especificada",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Control Interno",
    "descripcion": "Dashboard institucional de Matriz Estado de Avance Planes de Mejoramiento con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Matriz_Estado_de_Avance_Planes_de_Mejoramiento",
    "resumenDataset": "Datos relacionados con Matriz Estado de Avance Planes de Mejoramiento para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  },
  {
    "id": 52,
    "titulo": "Planes de Mejoramiento",
    "area": "Control Interno",
    "macroproceso": "Seguimiento",
    "subproceso": "Control Interno",
    "rol": "Administrativo",
    "url": "https://app.powerbi.com/view?r=eyJrIjoiYjFhMTE5MjgtZjRmZS00ZDQzLWE3ZTktNjMyZDdiNjRhODlkIiwidCI6IjA3ZGE2N2EwLTFmNDMtNGU4Yy05NzdmLTVmODhiNjQ3MGVlNiIsImMiOjR9",
    "fechaActualizacion": "15/10/2025",
    "fuente": "Sistemas de Información Institucionales",
    "elaboradoPor": "Control Interno",
    "descripcion": "Dashboard institucional de Planes de Mejoramiento con información actualizada y visualizaciones interactivas.",
    "estado": "Activo",
    "observaciones": "Dashboard gestionado por la dependencia responsable.",
    "esHistorico": false,
    "nombreDataset": "Planes_de_Mejoramiento",
    "resumenDataset": "Datos relacionados con Planes de Mejoramiento para el seguimiento institucional.",
    "columnas": [
      {"nombre": "id_registro", "tipo": "number", "descripcion": "Identificador único del registro"},
      {"nombre": "fecha_registro", "tipo": "date", "descripcion": "Fecha del registro"},
      {"nombre": "periodo", "tipo": "text", "descripcion": "Periodo de reporte"}
    ],
    "fuenteDataset": "Sistemas de Información Institucionales",
    "notasDataset": "Datos actualizados periódicamente según calendario institucional."
  }
];
